version: '3.7'

services: 
  artemis:
    container_name: artemis
    build: .
    env_file:
      - ${HOME}/env/artemis/.env
    volumes: 
      - ${HOME}/storage/artemis/public/pictures:/usr/src/app/public/pictures
    networks: 
      - database

networks: 
  database:
    external: 
      name: database