version: '3.7'

services: 
  artemis:
    container_name: artemis
    image: dhirawigata/artemis
    build: .
    env_file:
      - ${HOME}/env/artemis/.env
    volumes: 
      - ${HOME}/storage/artemis/public/pictures:/usr/src/app/public/pictures
      # - ${HOME}/env/artemis/.env:/usr/src/app/.env
    ports:
      - 3000:3000
    networks: 
      - database

networks: 
  database:
    external: 
      name: database